### ISSUE TITLE
Integrate STA for Eye Tracking Data

### ISSUE THREAD

**Issue by achadha0111** [IAM-lab/IAM-Framework#1]
## Implementation Plan
Build an inference module that can be applied through a slice like interface. This requires some background work, namely, the following things:

- [ ] Slice like interface design that allows one to define the data source, 

- [ ] Select the pre-processing steps that must be applied

- [ ] The visualisation that must be generated

- [ ] Inference parameters that must be used

In addition to this, the following things are needed in general:

- [ ] The inference module selection field should allow reordering. 

- [ ] The custom visualisation must be added to the list of standard superset ones. 

## Testing Plan

The following tests are required for the following scenarios:

- [ ] Test for non negative values for each of the STA parameters.

- [ ] Test for the participant length list being equal to the amount of participant data. 

- [ ] The URL provided for the webpage should be valid.
