### ISSUE TITLE
Build inference pipeline interface

### ISSUE THREAD

**Issue by achadha0111** [IAM-lab/IAM-Framework#2]
## Implementation Plan

- [ ] Build new view to hold components for setting up an inference pipeline.

- [ ] Add component to select data store. This might be tricky since you also need to add segmentation data in addition to the participant data.

- [ ] Component to set inference parameters.

- [ ] Component to set inference module and order them. 

- [ ] Option to select visualisation that needs to be generated. 

## Testing Plan:

Same as #1
